### ISSUE TITLE
Map does not load in FireFox (on first access or at all)

### ISSUE THREAD

**Issue by szabgab** [hasadna/anyway#650] opened 2017-01-11 08:22 UTC
Create a `New Private Window` in Firefox and visit https://www.anyway.co.il/ the top and bottom navigation bars load, but the map does not. In this Private window even reload does not seem to help.

I saw similar behavior in my "public" window and the map showed up after reloading the page.

**Comment by ChaosPredictor** [comment] 2017-02-27 19:18
Can't reproduction w/o Private mode. Private mode is duplication of #653

**Comment by r-darwish** [comment] 2017-09-10 13:00
Closeing as duplicate of #653

**Closed by r-darwish** 2017-09-10 13:00 UTC
Labels: bug
