### ISSUE TITLE
Localize Widget - most_severe_accidents_table

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1588] opened 2020-11-14 00:38 UTC
**Widget ID**
most_severe_accidents_table

**Widget Fields**
type

**Dictionaries Missing**
Dictionaries to create (For example - Accident Type Dictionary)
Note: Create a dictionary containing using the DB code as a key and not the Hebrew translation (for example `{1: 'fatal'}` rather than `{'קטלנית': 'fatal'}`)

**Widget Title**
Yes - title is : תאונות בסדר חומרה יורד במקטע ____

**Additional context**
- Existing translation to CBS fields - [see here](https://docs.google.com/spreadsheets/d/1qaVV7NKXVYNmnxKZ4he2MKZDAjWPHiHfq-U5dcNZM5k/edit#gid=375223389)
(Note - if translation in file is not adequate - please create a better translation)

**Comment by ziv17** [comment] 2020-12-02 16:52
Hi @atalyaalon , if we use the `flask_babel` structure, with `msgid`, do we still need the dictionaries?
We can set the `msgid` as the code in the database, e.g. `accident_type` in `AccidentMarker` table. We can set constants for readability. (or `Enum` :) )
What do you think?

**Comment by ziv17** [comment] 2020-12-14 20:04
Hi @atalyaalon is this issue a duplicate of #1578?

**Comment by atalyaalon** [comment] 2020-12-14 21:04
> Hi @atalyaalon , if we use the `flask_babel` structure, with `msgid`, do we still need the dictionaries?
> We can set the `msgid` as the code in the database, e.g. `accident_type` in `AccidentMarker` table. We can set constants for readability. (or `Enum` :) )
> What do you think?

sorry for the delay! 
I guess it depends on how we model our data.
For example - if we map a few vehicle types to one vehicle type - (for example, a few types of motorcycles) - then we'll need some dictionary (unrelated to flask babel) - that will map all motorcycle types to the single word "motorcycle".
BTW we can also make sure we'll have DB tables with these mapping.
In some cases - the mapping is exactly like the data in the DB, and in some cases we need to map the values first - and the localization comes afterwards.
So the question is - what is the best way to model this in a readable way, and make sure we take care of localization at the same time?

Perhaps @idosavion and Yaron can contribute to the discussion?

**Comment by atalyaalon** [comment] 2020-12-14 21:04
> Hi @atalyaalon is this issue a duplicate of #1578?

yes, closing #1578

**Closed** 2020-12-26 21:52 UTC
Labels: localization
