### ISSUE TITLE
Localization to English

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#310] opened 2015-06-09 07:21 UTC
In order to spread our idea and extend our community not only to people who understand hebrew we should allow people to choose to view the entire site in English. We already have the main file (AccData.csv) translated into english (link below).

Let's remember that car accidents are a universal problem and more minds thinking about it are more chances that we can eliminate deaths. 

Link to the file: https://docs.google.com/spreadsheets/d/1TxRQukcLzfno8kG-6eH_XEMrcuk2h8PNJOmY5IZUEzg/edit?usp=sharing

**Comment by omerxx** [comment] 2015-06-09 16:05
This also means translating the UI and changing it's structure (side bar to the left etc...)

**Comment by galraij** [comment] 2015-06-09 16:12
True, thanks for mentioning that!



‫ב-9 ביוני 2015, בשעה 19:05, ‏‏omerxx ‏<notifications@github.com> כתב/ה:‬

**Comment by aviklai** [comment] 2015-06-10 08:04
We can use the following solution:
http://l20n.org/

**Comment by danielhers** [comment] 2015-07-06 18:47
See #94

**Comment by danielhers** [comment] 2015-09-20 06:49
Duplicate of #94.

**Closed by danielhers** 2015-09-20 06:49 UTC
Labels: 1 - Ready, enhancement
