### ISSUE TITLE
Blue Markers of "Ihud Hazala" should have a color according to their severity

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#527] opened 2015-12-28 19:34 UTC
Blue Markers of "Ihud Hazala" should have a color according to their severity.

**Comment by bonnanza** [comment] 2016-01-22 05:56
Hi All, (nice to join.. :))

Do we want to show the 'ihud Hazala' unique icon and just give it the right color? 
like this:
![image](https://cloud.githubusercontent.com/assets/3808739/12503359/4bc2307e-c0dc-11e5-961e-61bf9f1162ee.png)

the other option is to show the same icon for all accident markers 
if the answer is yes, i think i found it..

**Comment by simonaho** [comment] 2016-01-22 06:03
Please leave the icon as is since there is a difference in the accuracy of the report. Thanks.

**Comment by bonnanza** [comment] 2016-01-29 09:25
duplicate of #493 
fixed.

**Closed** 2016-01-29 09:26 UTC
Labels: 2 - Working, bug, frontend, urgent

**Comment by galraij** [comment] 2016-01-30 23:07
I think regardless of accuracy issues that we will solve we should color the icons by severity. The severity is important and it’s data that we have so why won’t we use it?

**Comment by danielhers** [comment] 2016-01-31 07:45
@galraij, it's closed since it's solved :)
See on http://anyway-unstable.herokuapp.com/

**Comment by simonaho** [comment] 2016-01-31 09:02
@danielhers when do you plan to move from unstable to stable?

**Comment by danielhers** [comment] 2016-01-31 09:07
Probably tomorrow, if everything works right
