### ISSUE TITLE
Add a number to indicate number of accidents on the map

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#581] opened 2016-04-18 18:35 UTC
Add a number to indicate number of accidents on the map

**Comment by MoodyUser** [comment] 2016-04-18 18:46
![selection_002](https://cloud.githubusercontent.com/assets/15890521/14615572/fe02d8c6-05ae-11e6-8ee0-46d3d2218d1f.png)

**Comment by totalamd** [comment] 2017-02-06 18:06
Duplicate of putting the number of marker group members on aggregated icons #515

**Closed by totalamd** 2017-02-06 18:06 UTC
Labels: 2 - Working, enhancement, frontend
